CXXFLAGS =-ggdb -c -std=c++17 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
CFLAGS=-std =c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings

main: main.cpp
	g++ -ggdb -std=c++0x main.cpp -o main

