CXXFLAGS =-ggdb -c -std=c++0x -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
CFLAGS=-std =c99 -pedantic -Wall -Wextra -Werror -ansi -Wwrite-strings

testHash: testHash.cpp
	g++ -ggdb -std=c++0x testHash.cpp -o testHash

clean: 
	/bin/rm *core*
